# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0002_auto_20170831_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserOld',
        ),
    ]
